[module]
name = "badcompressloop5"
type = "feature"
info = "Pointer loop in CNAME field 2"
desc = "Respond with CNAME, where the CNAME only contains \"abc\" + a pointer to the beginning of the \"abc\" (=> a loop)."
author = "ivan.jedek@oryxlabs.com"
category = "Bad compression"

code = '''
if req.first_subdomain.startswith("badcompressloop5"):
   # Send answer with a compression pointer loop in the CNAME - variant 2
   ### DNS header ########
   buffer = prep_dns_header(b'\x84\x00', req.QURR, 1, 0, 0)
   ### QUESTION SECTION ########
   if resp.noq: buffer += convDom2Bin(req.full_domain) + req.type_bin + req.class_bin
   ### ANSWER SECTION ########
   # CNAME
   buffer += b"\xc0\x0c" + getTypeBin("CNAME") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                ## TTL
   offset_to_last_cname = len(req.full_domain) + 12 + 18     ## forward pointer to the CNAME in the end
   dom = b"\x03abc" + b"\xc0" + struct.pack(">B", offset_to_last_cname)
   buffer += struct.pack(">H", len(dom))                ## Data length
   buffer += dom                                        ## CNAME value with pointer to itself
   # log and send
   log("CNAME abc<LOOP> (badcomp loop 5 in CNAME)")
   send_buf(self, buffer)
   #####################################################################
'''
