[module]
name = "close"
type = "feature"
info = "Close the connection"
desc = "Don't respond, just close the connection immediately."
author = "ivan.jedek@oryxlabs.com"
category = "Empty responses"

code = '''
if req.first_subdomain.startswith("close"):
   # Close the connection
   log("just closing connection")
   time.sleep(resp.sleep)
   close_conn(self)
   #####################################################################
'''
