[module]
name = "empty6"
type = "feature"
info = "ANSWER section is missing"
desc = "Send normal DNS response, but remove the ANSWER section."
author = "ivan.jedek@oryxlabs.com"
category = "Empty responses"

code = '''
if req.first_subdomain.startswith("empty6"):
   # Send back a normal looking DNS response, but remove the ANSWER SECTION
   ### DNS header ########
   buffer = prep_dns_header(b'\x84\x00', req.QURR, 1, 0, 0)
   ### QUESTION SECTION ########
   if resp.noq: buffer += convDom2Bin(req.full_domain) + req.type_bin + req.class_bin
   ### ANSWER SECTION ######## - missing
   # log and send
   log("remove ANSWER section")
   send_buf(self, buffer)
   #####################################################################
'''
