[module]
name = "empty2"
info = "Only NULL bytes"
desc = "Send empty response with arbitrary number of NULLs (x00)."
type = "feature"
author = "ivan.jedek@oryxlabs.com"

code = '''
if req.first_subdomain.startswith("empty2"):
   # Send arbitrary number of NULLs
   nulls = 1 # number of NULLs to send
   if req.subdomains[1].isnumeric():
      nulls = int(req.subdomains[1])
   buffer = b"\x00" * nulls
   log("only %d NULL(s)" % (nulls))
   if proto == "tcp":
      send_buf_wo_len(self, buffer)
   else:
      send_buf(self, buffer)
   #####################################################################
'''
