[module]
name = "knot1poc"
info = ""
desc = ""
type = "feature"
author = "ivan.jedek@oryxlabs.com"

code = '''
if req.first_subdomain.startswith("knot1poc"):
   # Send arbitrary number of NULLs
   nulls = 2 # number of NULLs to send (by default 2)
   if req.subdomains[1].isnumeric():
      nulls = int(req.subdomains[1])
   buffer = b"\x00" * nulls
   log("only %d NULL(s)" % (nulls))
   if proto == "tcp":
      send_buf_wo_len(self, buffer)
   else:
      send_buf(self, buffer)
   #####################################################################
'''
