[module]
name = "nschain"
type = "feature"
info = "NS alias chain"
desc = "Respond with an incremented NS record. This creates an infinite alias chain."
author = "ivan.jedek@oryxlabs.com"
category = "Aliases, loops and chains"

code = '''
if req.first_subdomain.startswith("nschain"):
   # Send incremented NS alias
   new_domain_name = increment_chain(req.full_domain)
   ### DNS header ########
   buffer = prep_dns_header(b'\x84\x00', req.QURR, 1, 0, 0)
   ### QUESTION SECTION ########
   if resp.noq: buffer += convDom2Bin(req.full_domain) + req.type_bin + req.class_bin
   ### ANSWER SECTION ########
   # NS
   buffer += b'\xc0\x0c' if resp.compress else convDom2Bin(req.full_domain)
   buffer += getTypeBin("NS") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)                    ## TTL
   buffer += struct.pack(">H", len(new_domain_name)+2)      ## Data length
   buffer += convDom2Bin(new_domain_name)                   ## NS value
   # log and send
   log("NS %s" % (new_domain_name))
   send_buf(self, buffer)
   #####################################################################
'''
