[module]
name = "queryback2"
info = "Query reflection, stripped"
desc = "Send back the same query, stripped. Send back only the same question, without any additional sections (e.g. the OPT / EDNS0)."
type = "feature"
author = "ivan.jedek@oryxlabs.com"

code = '''
if req.first_subdomain.startswith("queryback2"):
   # Domain starts with "queryback2", let's send back the same query - stripped, with only
   # the question without any additional sections (like e.g. the OPT / EDNS0)
   ### DNS header ########
   buffer = prep_dns_header(req_FLAGS, req.QURR, 0, 0, 0)
   ### QUESTION SECTION ########
   if resp.noq: buffer += convDom2Bin(req.full_domain) + req.type_bin + req.class_bin
   # log and send
   log("sending back the same query - stripped")
   send_buf(self, buffer)
   #####################################################################
'''
