[module]
name = "queryback1"
type = "feature"
info = "Query reflection"
desc = "Instead of a proper response, send back the exact same query."
author = "ivan.jedek@oryxlabs.com"
category = "Empty responses"

code = '''
if req.first_subdomain.startswith("queryback1"):
   # Domain starts with "queryback1", let's send back the same query
   buffer = resp.ID + req.RAW[2:]
   # log and send
   log("sending back the same query")
   send_buf(self, buffer)
   #####################################################################
'''
