[module]
name = "spfalias1"
type = "feature"
info = "TXT SPF random N aliases"
desc = "Respond with N number of SPF(TXT) aliases containing random chain index (`spfalias####.yourdomain.com`). BEWARE: This could result in multiplication."
author = "ivan.jedek@oryxlabs.com"
category = "Aliases, loops and chains"

code = '''
           elif req.first_subdomain.startswith("spfalias1"):
              # Send multiple SPF (TXT) records with a random alias in the include parameter
              # BEWARE: This could result in multiplication
              answers = int(req.subdomains[1]) if req.subdomains[1].isnumeric() else 1
              ### DNS header ########
              buffer = prep_dns_header(b'\x84\x00', req.QURR, answers, 0, 0)
              ### QUESTION SECTION ########
              if resp.noq: buffer += convDom2Bin(req.full_domain) + req.type_bin + req.class_bin
              ### ANSWER SECTION ########
              doms = []
              for i in range(answers):
                  # TXT SPF
                  dom = name_fuzz(resp.nfz) if hasattr(resp, "nfz") else "spfalias1" + str(random.getrandbits(20) % 100000) + "." + ".".join(req.subdomains[1:])
                  data = "v=spf1 include:" + dom + " ~all"
                  buffer += b'\xc0\x0c' if resp.compress else convDom2Bin(req.full_domain)
                  buffer += getTypeBin("TXT") + getClassBin("IN")
                  buffer += struct.pack(">L", resp.TTL)      ## TTL
                  buffer += struct.pack(">H", len(data)+1)   ## Data length (2B)
                  buffer += struct.pack(">B", len(data))     ## TXT length (1B)
                  buffer += data.encode("utf-8")             ## TXT SPF value
                  doms.append(dom)
              # log and send
              log("%d SPF(TXT) aliases: %s" % (answers, ', '.join(map(str, doms[:3])) + (', ...' if answers > 3 else '')))
              send_buf(self, buffer)
              #####################################################################
'''
