[module]
name = "spfchain"
type = "feature"
info = "TXT SPF alias chain"
desc = "Respond with an incremented SPF(TXT) record. This creates an infinite alias chain."
author = "ivan.jedek@oryxlabs.com"
category = "Aliases, loops and chains"

code = '''
if req.first_subdomain.startswith("spfchain"):
   # Send incremented SPF(TXT) alias
   new_domain_name = increment_chain(req.full_domain)
   ### DNS header ########
   buffer = prep_dns_header(b'\x84\x00', req.QURR, 1, 0, 0)
   ### QUESTION SECTION ########
   if resp.noq: buffer += convDom2Bin(req.full_domain) + req.type_bin + req.class_bin
   ### ANSWER SECTION ########
   # TXT SPF
   buffer += b'\xc0\x0c' if resp.compress else convDom2Bin(req.full_domain)
   data = "v=spf1 include:" + new_domain_name + " ~all"
   buffer += getTypeBin("TXT") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)       ## TTL
   buffer += struct.pack(">H", len(data)+1)    ## Data length (2B)
   buffer += struct.pack(">B", len(data))      ## TXT length (1B)
   buffer += data.encode("utf-8")              ## TXT SPF value
   # log and send
   log("SPF(TXT) %s" % (new_domain_name))
   send_buf(self, buffer)
   #####################################################################
'''
