[module]
name = "timeout"
type = "feature"
info = "Don't respond"
desc = "Don't respond, just let the connection timeout."
author = "ivan.jedek@oryxlabs.com"
category = "Empty responses"

code = '''
if req.first_subdomain.startswith("timeout"):
   # Timeout the connection
   log("sending nothing (timeout)")
   timeout_conn(self)
   #####################################################################
'''
