dnssec:
  validation: off
logging:
  common_errors: true
  loglevel: 7
  trace: true
  quiet: false
incoming:
  allow_from:
    - 127.0.0.0/8
    - ::1
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  listen:
    - 0.0.0.0
  port: 53
recursor:
  forward_zones:
    - zone: yourdomain.com
      forwarders:
        - 192.168.0.11
  include_dir: /etc/powerdns/recursor.d
