title: PolarDNS Documentation
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
kramdown:
  input: GFM

# Theme settings:
repo_url: "https://github.com/oryxlabs/PolarDNS"
edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist

aux_links_new_tab: true
aux_links:
  "View PolarDNS on GitHub":
    - "https://github.com/oryxlabs/PolarDNS"

just_the_docs:
  show_toc: true # Enable TOC globally
  toc_levels: "1..3" # Show headers from level 1 to 3

