name: E2E BIND 9
on:
  - workflow_dispatch
jobs:
  tests:
    runs-on: [linux, self-hosted]
    strategy:
      matrix:
        version:
          - "9.18"
          - "9.20"
          - "9.21"
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@v4

      - name: Run Bind9
        run: |
          docker run --name bind9 -p 10053:53/udp -p 10053:53/tcp -d -v "${{ github.workspace }}/.github/workflows/e2e-bind9/named.conf:/etc/bind/named.conf" internetsystemsconsortium/bind9:${{ matrix.version }}
          sleep 10

      - name: Run PolarDNS
        uses: ./.github/actions/run-polardns
        with:
          resolver: bind9

      - name: Run E2E tests
        uses: ./.github/actions/e2e-tests
        continue-on-error: true

      - name: Collect Docker logs
        run: |
          mkdir -p test-e2e/debug
          docker ps -a >test-e2e/debug/docker.log 2>&1

      - name: Collect Bind9 logs
        run: |
          docker logs bind9 >test-e2e/debug/bind9.log 2>&1

      - name: Collect PolarDNS logs
        run: |
          docker logs polardns >test-e2e/debug/polardns.log 2>&1

      - name: Compress test results
        run: tar -czf test-e2e-results-bind9-${{ matrix.version }}.tar.gz -C test-e2e .

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          path: test-e2e-results-bind9-${{ matrix.version }}.tar.gz
          name: test-e2e-results-bind9-${{ matrix.version }}
          if-no-files-found: ignore

