name: E2E BIND 9
on:
  - workflow_dispatch
jobs:
  tests:
    runs-on: [linux, self-hosted]
    strategy:
      matrix:
        version:
          - "9.18"
          - "9.20"
          - "9.21"
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@v4

      - name: Run Bind9
        run: |
          docker run --name bind9 -p 10053:53/udp -p 10053:53/tcp -d -v "${{ github.workspace }}/.github/workflows/e2e-bind9/named.conf:/etc/bind/named.conf" internetsystemsconsortium/bind9:${{ matrix.version }}
          sleep 10

      - name: Run PolarDNS
        uses: ./.github/actions/run-polardns
        with:
          resolver: bind9

      - name: Run E2E tests
        uses: ./.github/actions/e2e-tests
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          path: e2e-tests
          name: e2e-test-results-bind9-${{ matrix.version }}
          if-no-files-found: ignore

      - name: Debug running containers
        if: failure()
        run: |
          docker ps -a

      - name: Debug Bind9
        if: failure()
        run: |
          docker logs Bind9

      - name: Debug PolarDNS
        run: |
          docker logs polardns
